unit MemberFollowUp.Baas.Keys;

interface

{ WARNING: DO NOT INCLUDE THIS IN THE REPOSITORY COMMITS THIS IS YOUR APPLICATION SPECIFIC SETTINGS }

const
  MEMBERFOLLOWUP_PARSE_APPLICATIONID = 'xC5gDkiH6d3gjlmoU8PeowZiND4PxF3oOwuOEP2w';
//  MEMBERFOLLOWUP_PARSE_MASTERKEY     = '';
  MEMBERFOLLOWUP_PARSE_RESTAPIKEY    = 'MiVqXaD5TMac355FZDOEpaDksVCdHRcXtxEt21WK';


//const
//  MEMBERFOLLOWUP_KINVEY_


implementation

end.
